name: Release Workflow

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  nuget_source: https://nuget.pkg.github.com/reliaboe/index.json
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
        package_name: Demo.Core
    defaults:
        run:
          working-directory: ./App
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release ${{env.package_name}} --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity quiet

      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: v0.65.0

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'
          skip-setup-trivy: true

      - name: Package Nuget
        run: dotnet pack -c Release --output . --include-source --include-symbols  --no-build -p:PackageVersion=${{ github.event.release.tag_name }} ${{env.package_name}}

      - name: Package Source
        run: dotnet nuget add source --username reliaboe --password ${{ secrets.PACKAGE_WRITE }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/reliaboe/index.json"

      - name: Push
        run: dotnet nuget push ${{env.package_name}}.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.PACKAGE_WRITE }} --source "github" --skip-duplicate

