name: Release Workflow

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  nuget_source: https://nuget.pkg.github.com/reliaboe/index.json
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
        package_name: Demo.Core
    defaults:
        run:
          working-directory: ./app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release ${{env.package_name}} --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity quiet

      - name: Package Nuget
        run: dotnet pack -c Release --output . --include-source --include-symbols  --no-build -p:PackageVersion=${{ github.event.release.tag_name }} ${{env.package_name}}

      - name: Push
        run: dotnet nuget push ${{env.package_name}}.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.PACKAGE_WRITE }} --source "github" --skip-duplicate

